version: "3.9"

x-etcd-variables: &etcd-variables
  ALLOW_NONE_AUTHENTICATION: "yes"
  ETCD_LOG_LEVEL: warn
  ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
  ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2181
  ETCD_INITIAL_CLUSTER_TOKEN: token-01
  ETCD_INITIAL_CLUSTER: ${NAME_1}=http://${HOST_1}:2380,${NAME_2}=http://${HOST_2}:2380,${NAME_3}=http://${HOST_3}:2380
  ETCD_INITIAL_CLUSTER_STATE: new

x-postgres-variables: &postgres-variables
  PGPASSWORD: admin
  PGUSER: postgres
  PGREPLICATION_PASSWORD: replicator
  ETCD_CLUSTER: "${HOST_1}:2181 ${HOST_2}:2181 ${HOST_3}:2181"
  LOG_LEVEL: debug

services:
  etcd1:
    container_name: etcd1
    image: quay.io/coreos/etcd
    hostname: etcd1
    environment:
      <<: *etcd-variables
      ETCD_NAME: ${NAME_1}
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://${HOST_1}:2380
      ETCD_ADVERTISE_CLIENT_URLS: http://${HOST_1}:2181

  etcd2:
    container_name: etcd2
    image: quay.io/coreos/etcd
    hostname: etcd2
    environment:
      <<: *etcd-variables
      ETCD_NAME: ${NAME_2}
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://${HOST_2}:2380
      ETCD_ADVERTISE_CLIENT_URLS: http://${HOST_2}:2181

  etcd3:
    container_name: etcd3
    image: quay.io/coreos/etcd
    hostname: etcd3
    environment:
      <<: *etcd-variables
      ETCD_NAME: ${NAME_3}
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://${HOST_3}:2380
      ETCD_ADVERTISE_CLIENT_URLS: http://${HOST_3}:2181

  postgresql:
    container_name: node_1
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "5432:5432"
      - "8085:8080"
    environment:
      <<: *postgres-variables
      HOSTNAME: postgresql
    restart: on-failure

  postgresql2:
    container_name: node_2
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "5001:5432"
      - "8086:8080"
    environment:
      <<: *postgres-variables
      HOSTNAME: postgresql2
    restart: on-failure

  postgresql3:
    container_name: node_3
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "5002:5432"
      - "8087:8080"
    environment:
      <<: *postgres-variables
      HOSTNAME: postgresql3
    restart: on-failure

  pgbench:
    build:
      dockerfile: pgbench.Dockerfile
      context: pgbench/
    restart: always # Run continuously
    environment:
      <<: *postgres-variables
    depends_on:
      - etcd1
      - etcd2
      - etcd3
      - postgresql
      - postgresql2
      - postgresql3